<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2021-2030</name>
   <tag></tag>
   <elementGuidId>e85a8f83-8fd9-48d2-89c7-11bf80afb50c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-finance-menu']/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;2021-2030&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ea1348d5-0659-4a41-b327-42eff0e6f877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>annual_report.php?year=2021</value>
      <webElementGuid>1d072f1a-767e-4a78-a5ff-143c8ac11d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2021-2030</value>
      <webElementGuid>d9bf5fae-6d06-42fc-9790-55dcfbe078c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-finance-menu&quot;)/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom current-menu-item menu-item-5818&quot;]/a[1]</value>
      <webElementGuid>1dda63fc-a922-4d77-b145-482fe58abeb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-finance-menu']/li[6]/a</value>
      <webElementGuid>c38e54eb-02fd-45fb-b9d4-30e5552fca87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2021-2030')]</value>
      <webElementGuid>50f29a14-76fd-4e2a-a505-b8c3e5b44101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAGAZINES'])[1]/following::a[6]</value>
      <webElementGuid>8b33e13c-2cba-4dd3-9424-3e2259703b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[3]/following::a[6]</value>
      <webElementGuid>9b8ee825-4a63-47a8-90b3-dc9946be9196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Academic Year 1974-1975'])[1]/preceding::a[1]</value>
      <webElementGuid>871d03a5-fc0b-414f-93ee-05908467b3e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Academic Year 1976-1977'])[1]/preceding::a[2]</value>
      <webElementGuid>7451b923-adf1-497f-b7c0-605861f66bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2021-2030']/parent::*</value>
      <webElementGuid>b2523289-5b0f-48b2-b3a9-da5c9f903aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'annual_report.php?year=2021')])[3]</value>
      <webElementGuid>c8f99392-c476-41db-b2bb-d8ac31998819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/ul/li[6]/a</value>
      <webElementGuid>da0d0e01-fc30-4c04-bb46-aea15287e516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'annual_report.php?year=2021' and (text() = '2021-2030' or . = '2021-2030')]</value>
      <webElementGuid>00e9bd2e-f9e0-4684-805d-ed2a3c7e473e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
