<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_91-4563-222767</name>
   <tag></tag>
   <elementGuidId>4b0f1518-f146-43b8-b40d-c1dc02a1421e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='span_1dd7_11']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#span_1dd7_11 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=contentinfo >> internal:role=link[name=&quot;+91-4563-222767&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e24e39e2-48ce-4fe6-8910-e4f00e6e754e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>tel:914563222767</value>
      <webElementGuid>515a9fd7-3322-437c-8412-cfecb8d895f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+91-4563-222767</value>
      <webElementGuid>8f219b5a-a13f-42da-9f8c-a1636e42ed45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;span_1dd7_11&quot;)/a[1]</value>
      <webElementGuid>8563c560-998d-48d0-ba09-ebf296c51167</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_1dd7_11']/a</value>
      <webElementGuid>4eb7f626-ff51-4487-8957-ad4e92add29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'+91-4563-222767')])[2]</value>
      <webElementGuid>dc0b0b77-2a4c-4fec-8760-5d6b20a07340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rrc1973@gmail.com'])[3]/preceding::a[1]</value>
      <webElementGuid>4a4b7645-f4c6-46ba-926d-2aa7e8b11bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Campus'])[1]/preceding::a[2]</value>
      <webElementGuid>a6d36670-c9dd-42b0-8d1f-bab91986ee51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'tel:914563222767')])[3]</value>
      <webElementGuid>200c81b8-1d67-447b-a611-c5f2fb5183f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>eec86e5b-5e65-4f49-b5fd-249eaae9bac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'tel:914563222767' and (text() = '+91-4563-222767' or . = '+91-4563-222767')]</value>
      <webElementGuid>804fc2a6-0b73-484a-a7f3-88b7d8223d7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
