<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__ndfHFb-c4YZDc-cYSp0e-DARUcf-hSRGPd</name>
   <tag></tag>
   <elementGuidId>1f9acf06-3217-49ac-be2a-df23735afac9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, 'https://drive.google.com/file/d/1cysl-34k6XR168D3sYrJhYSdFlDai0x7/view?usp=drive_link')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a:nth-child(23)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cc765de0-6dd1-4aa2-b315-566c608d5877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://drive.google.com/file/d/1cysl-34k6XR168D3sYrJhYSdFlDai0x7/view?usp=drive_link</value>
      <webElementGuid>540e4f0d-ac43-47fa-b0c5-535010cb6813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>22cfad0f-b3a0-4155-af85-35c113302135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ndfHFb-c4YZDc-cYSp0e-DARUcf-hSRGPd</value>
      <webElementGuid>7a3f5e00-f7a6-48c4-8c4a-29ed45cfcb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d2f0f353-570b-4f34-8992-c5aa6d8fc638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>074354ec-f47e-42a2-b325-e90474caf42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>https://drive.google.com/file/d/1cysl-34k6XR168D3sYrJhYSdFlDai0x7/view?usp=drive_link</value>
      <webElementGuid>c06ab063-090b-4a84-ad44-75366a147124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://drive.google.com/file/d/1cysl-34k6XR168D3sYrJhYSdFlDai0x7/view?usp%3Ddrive_link&amp;sa=D&amp;source=apps-viewer-frontend&amp;ust=1718443347798097&amp;usg=AOvVaw08RB-gYF4UZU9UTGpv3clC&amp;hl=en-GB</value>
      <webElementGuid>04a6140f-5724-44f5-87a3-1fb26dd72845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>2614c518-e536-4c65-ac6e-3ff6adccc2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;yYWAMb bvmRsc vhoiae LgGVmb ndfHFb-c4YZDc-uoC0bf ndfHFb-c4YZDc-qbOKL-OEVmcd&quot;]/div[@class=&quot;ndfHFb-c4YZDc ndfHFb-c4YZDc-AHmuwe-Hr88gd-OWB6Me dif24c bvmRsc ndfHFb-c4YZDc-TSZdd ndfHFb-c4YZDc-vyDMJf-aZ2wEe ndfHFb-c4YZDc-i5oIFb vhoiae LgGVmb ndfHFb-c4YZDc-uoC0bf&quot;]/div[@class=&quot;ndfHFb-c4YZDc-K9a4Re&quot;]/div[@class=&quot;ndfHFb-c4YZDc-K9a4Re-nKQ6qf ndfHFb-c4YZDc-TvD9Pc-qnnXGd&quot;]/div[@class=&quot;ndfHFb-c4YZDc-cYSp0e ndfHFb-c4YZDc-oKVyEf&quot;]/div[@class=&quot;ndfHFb-c4YZDc-cYSp0e-s2gQvd ndfHFb-c4YZDc-s2gQvd&quot;]/div[@class=&quot;ndfHFb-c4YZDc-cYSp0e-Oz6c3e ndfHFb-c4YZDc-neVct-RCfa3e ndfHFb-c4YZDc-cYSp0e-DARUcf-gSKZZ&quot;]/div[@class=&quot;ndfHFb-c4YZDc-cYSp0e-DARUcf&quot;]/div[@class=&quot;ndfHFb-c4YZDc-cYSp0e-DARUcf-PLDbbf&quot;]/a[@class=&quot;ndfHFb-c4YZDc-cYSp0e-DARUcf-hSRGPd&quot;]</value>
      <webElementGuid>71895878-ea13-4d46-96bf-25b45d796d94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://drive.google.com/file/d/1cysl-34k6XR168D3sYrJhYSdFlDai0x7/view?usp=drive_link')]</value>
      <webElementGuid>1bfc5bdb-4ada-4ca6-a3b0-2b1026ac7196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[23]</value>
      <webElementGuid>b1e08c60-203f-4d89-9be6-f769bddd0f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://drive.google.com/file/d/1cysl-34k6XR168D3sYrJhYSdFlDai0x7/view?usp=drive_link']</value>
      <webElementGuid>e73fd974-f1cb-4ec5-b561-cbc315dd9702</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
