<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Academic Year 1982-1983</name>
   <tag></tag>
   <elementGuidId>7bbc0816-cb88-415a-bee4-c2bcb1bcd8a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rrc-page-wrapper']/div/div/div/div/div/div/div/div[2]/div[6]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Academic Year 1982-1983&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>835c23a4-c46e-48c9-ab52-b5180e5cbc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gdlr-core-personnel-list-button gdlr-core-button</value>
      <webElementGuid>a070bacb-e709-4682-b6db-7f1efabc3105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>50fb01f0-7a27-4a65-89de-311ee96d0841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>images/annual_reports/1982-1983.pdf</value>
      <webElementGuid>ac302cf1-3fd5-4bf0-bbd8-0cb80a0f5737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Academic Year 1982-1983</value>
      <webElementGuid>6d62cce1-a3f2-4d7f-baed-53f32acbcbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rrc-page-wrapper&quot;)/div[@class=&quot;gdlr-core-page-builder-body&quot;]/div[@class=&quot;gdlr-core-pbf-section&quot;]/div[@class=&quot;gdlr-core-pbf-section-container gdlr-core-container clearfix&quot;]/div[@class=&quot;gdlr-core-pbf-element&quot;]/div[@class=&quot;gdlr-core-blog-item gdlr-core-item-pdb clearfix  gdlr-core-style-blog-image&quot;]/div[@class=&quot;gdlr-core-portfolio-item-holder gdlr-core-js-2 filter-container clearfix&quot;]/div[@class=&quot;gdlr-core-pbf-element&quot;]/div[@class=&quot;gdlr-core-personnel-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-personnel-item-style-medium gdlr-core-personnel-style-medium&quot;]/div[@class=&quot;gdlr-core-personnel-list-column  gdlr-core-column-40 gdlr-core-column-first gdlr-core-item-pdlr&quot;]/div[@class=&quot;gdlr-core-personnel-list clearfix&quot;]/div[@class=&quot;gdlr-core-personnel-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-personnel-item-style-medium gdlr-core-personnel-style-medium&quot;]/a[@class=&quot;gdlr-core-personnel-list-button gdlr-core-button&quot;]</value>
      <webElementGuid>275ab64f-9c3a-4b67-9b59-5a94edee7986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rrc-page-wrapper']/div/div/div/div/div/div/div/div[2]/div[6]/div/div/a</value>
      <webElementGuid>ff26eab0-105a-44ce-b615-86b9e79884b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Academic Year 1982-1983')]</value>
      <webElementGuid>7cd4c9e4-2376-4626-a05b-d36f9ef6dfdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Academic Year 1980-1981'])[1]/following::a[1]</value>
      <webElementGuid>50c1bc83-7af0-482b-b741-c187bd97da31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Academic Year 1979-1980'])[1]/following::a[2]</value>
      <webElementGuid>76db5b38-6c6d-4a99-a404-94a47142ba06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::a[1]</value>
      <webElementGuid>161c2c81-3673-4eb6-a32f-ef1345083434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Academic Year 1982-1983']/parent::*</value>
      <webElementGuid>f367edfb-1186-49ca-a0bb-df8022b23354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'images/annual_reports/1982-1983.pdf')]</value>
      <webElementGuid>5b6e7f5c-90f0-4a02-b3c8-56ad2531a29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/a</value>
      <webElementGuid>439c8b13-f26d-4406-86f2-89beadd68069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'images/annual_reports/1982-1983.pdf' and (text() = 'Academic Year 1982-1983' or . = 'Academic Year 1982-1983')]</value>
      <webElementGuid>4a64e11b-af61-4f01-88b2-d3f006120b50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
