<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Code of Conduct</name>
   <tag></tag>
   <elementGuidId>f5e74d11-a122-4a96-a380-4022e83297ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-our-campus']/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Code of Conduct&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2037ab6-5d88-43e7-8393-f87f2a384929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>code_conduct.php</value>
      <webElementGuid>c4e5b114-fac9-41d1-ba2b-d7cff1341a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Code of Conduct</value>
      <webElementGuid>752f7eed-5740-4944-a9f3-619e564ed1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js rrc-mmenu-right&quot;]/body[@class=&quot;home page-template-default page page-id-2039 gdlr-core-body woocommerce-no-js tribe-js rrc-body rrc-body-front rrc-full  rrc-with-sticky-navigation  rrc-blockquote-style-1 gdlr-core-link-to-lightbox&quot;]/footer[1]/div[@class=&quot;rrc-footer-wrapper&quot;]/div[@class=&quot;rrc-footer-container rrc-container clearfix&quot;]/div[@class=&quot;rrc-footer-column rrc-item-pdlr rrc-column-15&quot;]/div[@id=&quot;gdlr-core-custom-menu-widget-2&quot;]/div[@class=&quot;menu-our-campus-container&quot;]/ul[@id=&quot;menu-our-campus&quot;]/li[@class=&quot;menu-item&quot;]/a[1]</value>
      <webElementGuid>70527782-22a7-4561-8fca-e070febc2954</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-our-campus']/li[4]/a</value>
      <webElementGuid>4e3ead38-f8ad-4c2c-ae6a-615a655ad89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Code of Conduct')])[3]</value>
      <webElementGuid>670cb48d-2f9a-45ab-a689-bdf807546806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vision, Mission &amp; Core Values'])[1]/following::a[1]</value>
      <webElementGuid>a87aae14-098e-4b6e-915f-5a03b973e714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Institution'])[2]/following::a[2]</value>
      <webElementGuid>9679fcc6-7718-4339-a5cf-166dbdcfbb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Academic Council'])[3]/preceding::a[1]</value>
      <webElementGuid>6d26c547-adf3-4b1c-b601-58ff2c160928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Magazines'])[2]/preceding::a[2]</value>
      <webElementGuid>c6451989-41bf-4fdf-ad8a-1caa4247111a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'code_conduct.php')]</value>
      <webElementGuid>071f2f1b-b873-4a52-a937-acf5ea16579a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div[2]/div/div/ul/li[4]/a</value>
      <webElementGuid>84debf67-8126-4ac0-b195-25d457965cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'code_conduct.php' and (text() = 'Code of Conduct' or . = 'Code of Conduct')]</value>
      <webElementGuid>fadf6f1d-4840-43f0-a3bb-23ce0c957556</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
