<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Faculty</name>
   <tag></tag>
   <elementGuidId>5fa413c9-baef-4ebd-b143-338126feb60a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-main-navigation-1']/li[3]/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.sub-menu > li.menu-item.sfHover > a.sf-with-ul-pre</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Faculty &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4209e80a-6faf-48f4-a20d-c0150369ce7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>38ae5538-3ed4-4a36-8c56-53b46aaf7e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sf-with-ul-pre</value>
      <webElementGuid>ce1f6ec5-ff95-4de5-8bd6-8eb71ff82ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Faculty</value>
      <webElementGuid>71e00292-3021-4d7a-9e46-4b6d1d6d8ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-main-navigation-1&quot;)/li[@class=&quot;menu-item menu-item-has-children rrc-normal-menu sfHover&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@class=&quot;menu-item sfHover&quot;]/a[@class=&quot;sf-with-ul-pre&quot;]</value>
      <webElementGuid>579906e7-d540-49ad-a989-2d84bb22a8d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-main-navigation-1']/li[3]/ul/li[2]/a</value>
      <webElementGuid>f839d596-2578-4295-8531-453df04b795d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Faculty')])[3]</value>
      <webElementGuid>95b22bef-e6a8-4fcf-a6bd-3c09e35161fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departments'])[2]/following::a[1]</value>
      <webElementGuid>f1b08e77-c1a1-48bb-bfd6-83b061d4b133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Magazines'])[2]/following::a[3]</value>
      <webElementGuid>62234547-ee86-460b-8460-9ae36067fd04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aided'])[4]/preceding::a[1]</value>
      <webElementGuid>e6063920-e58f-44ee-88f4-95af22f6ed6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self Finance'])[4]/preceding::a[2]</value>
      <webElementGuid>3d1695fc-aa58-412d-a4b1-071a5ca665a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[50]</value>
      <webElementGuid>4e286e80-b7af-44dc-9002-f019a31238e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/a</value>
      <webElementGuid>fc1460db-8a5d-44ec-9e7f-128ad5328ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Faculty' or . = 'Faculty')]</value>
      <webElementGuid>b36674fa-27b6-4df7-b38a-7aada9c96951</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
