<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Magazines</name>
   <tag></tag>
   <elementGuidId>1b96f6a3-b334-4515-b134-c66b8a7e9e5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-our-campus']/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Magazines&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba4d5288-c142-4139-bfa2-99ba145775b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>annual_report.php?year=1973</value>
      <webElementGuid>aa9e2b3a-16a6-4ce5-b933-abcf61b19db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Magazines</value>
      <webElementGuid>800c829a-1168-4daa-adc7-21f2086f863e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mm-0&quot;)/div[@class=&quot;rrc-body-wrapper clearfix  rrc-with-frame&quot;]/footer[1]/div[@class=&quot;rrc-footer-wrapper&quot;]/div[@class=&quot;rrc-footer-container rrc-container clearfix&quot;]/div[@class=&quot;rrc-footer-column rrc-item-pdlr rrc-column-15&quot;]/div[@id=&quot;gdlr-core-custom-menu-widget-2&quot;]/div[@class=&quot;menu-our-campus-container&quot;]/ul[@id=&quot;menu-our-campus&quot;]/li[@class=&quot;menu-item&quot;]/a[1]</value>
      <webElementGuid>5a7a762e-f987-46a1-a89d-15364c1e8ae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-our-campus']/li[6]/a</value>
      <webElementGuid>47e88176-da75-4c0c-9ed8-424d668de33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Magazines')])[2]</value>
      <webElementGuid>5c225daa-229c-4f38-bb48-1d0c399a4461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Academic Council'])[2]/following::a[1]</value>
      <webElementGuid>59a1e138-32b0-4f7e-bc06-464eadea0048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code of Conduct'])[5]/following::a[2]</value>
      <webElementGuid>b090c816-574e-4f20-8396-6349b94aba82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Academics'])[3]/preceding::a[1]</value>
      <webElementGuid>471f7254-cf7a-471f-828e-6be927265af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departments'])[2]/preceding::a[1]</value>
      <webElementGuid>f872db3a-6cfe-494c-8666-77295cf6a15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'annual_report.php?year=1973')]</value>
      <webElementGuid>73d92657-c8c2-4965-8d74-30fdf6a43b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div[2]/div/div/ul/li[6]/a</value>
      <webElementGuid>e93e09a8-4fc6-41ca-a4b0-275b4fae274f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'annual_report.php?year=1973' and (text() = 'Magazines' or . = 'Magazines')]</value>
      <webElementGuid>d87c7866-fa31-4d8a-b974-4f6de71cb283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
