<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_rrc1973gmail.com</name>
   <tag></tag>
   <elementGuidId>c1dcc129-07b4-4de6-8d09-3912a6b820bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='i_fd84_0'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > #i_fd84_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=contentinfo >> internal:role=link[name=&quot;rrc1973@gmail.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>16467d4a-b4ca-4fc5-ab40-3e38d568d610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i_fd84_0</value>
      <webElementGuid>f0d58f1d-bdb1-43a9-9cf3-2e953d155991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mail.google.com/mail/?view=cm&amp;fs=1&amp;tf=1&amp;to=rrc1973@gmail.com</value>
      <webElementGuid>ca54c7e9-b989-4e0d-94f2-492f8f24511f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>e83d05cf-5ebc-41c3-8f74-b0c365e71ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rrc1973@gmail.com</value>
      <webElementGuid>ed4e0e19-4c85-4f6d-8c8d-4370566206ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mm-0&quot;)/div[@class=&quot;rrc-body-wrapper clearfix  rrc-with-frame&quot;]/footer[1]/div[@class=&quot;rrc-footer-wrapper&quot;]/div[@class=&quot;rrc-footer-container rrc-container clearfix&quot;]/div[@class=&quot;rrc-footer-column rrc-item-pdlr rrc-column-15&quot;]/div[@id=&quot;gdlr-core-custom-menu-widget-2&quot;]/div[@class=&quot;menu-our-campus-container&quot;]/ul[@id=&quot;menu-our-campus&quot;]/li[3]/a[@id=&quot;i_fd84_0&quot;]</value>
      <webElementGuid>38634927-98b7-4d19-84a4-b811c894cf77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='i_fd84_0'])[3]</value>
      <webElementGuid>696246a1-2d81-4a10-9d47-f9cda3b37c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-our-campus']/li[3]/a</value>
      <webElementGuid>d5760829-3b3e-407e-9149-d37b3cfe5119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'rrc1973@gmail.com')])[3]</value>
      <webElementGuid>1b266348-b4a9-45b8-9731-40a851dc15d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Campus'])[1]/preceding::a[1]</value>
      <webElementGuid>a1e5d234-c3aa-43af-85b3-4a755ba0415e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='College Governing Council'])[2]/preceding::a[1]</value>
      <webElementGuid>59569ac2-ebdd-44a2-88c8-ced9769abbfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://mail.google.com/mail/?view=cm&amp;fs=1&amp;tf=1&amp;to=rrc1973@gmail.com')])[3]</value>
      <webElementGuid>b60765c9-9f5d-4bcd-8219-f3d0845fc7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div/div/div/ul/li[3]/a</value>
      <webElementGuid>a46a4e6e-66d1-478a-8b05-1ab0944d07d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'i_fd84_0' and @href = 'https://mail.google.com/mail/?view=cm&amp;fs=1&amp;tf=1&amp;to=rrc1973@gmail.com' and (text() = 'rrc1973@gmail.com' or . = 'rrc1973@gmail.com')]</value>
      <webElementGuid>bdedd7bc-8905-4e15-af45-e69d7118743e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
