<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GALLERY</name>
   <tag></tag>
   <elementGuidId>6cecd56a-fd66-4f48-9869-4c069ce93f41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rrc-page-wrapper']/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;GALLERY&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eccff818-a1c1-45c2-926d-526b8e5873bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gdlr-core-tab-item-title</value>
      <webElementGuid>d12494d6-9a67-43d8-b4b0-1066d6f50d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab-id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c2b83692-59da-49b1-a402-a6f5226fc715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GALLERY</value>
      <webElementGuid>440d68f3-fbca-41ee-a159-220112f45118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rrc-page-wrapper&quot;)/div[@class=&quot;gdlr-core-page-builder-body&quot;]/div[@class=&quot;gdlr-core-pbf-section&quot;]/div[@class=&quot;gdlr-core-pbf-section-container gdlr-core-container clearfix&quot;]/div[@class=&quot;gdlr-core-pbf-element&quot;]/div[@class=&quot;gdlr-core-blog-item gdlr-core-item-pdb clearfix  gdlr-core-style-blog-image&quot;]/div[@class=&quot;gdlr-core-pbf-wrapper&quot;]/div[@class=&quot;gdlr-core-pbf-wrapper-content gdlr-core-js&quot;]/div[@class=&quot;gdlr-core-pbf-wrapper-container clearfix gdlr-core-container&quot;]/div[@class=&quot;gdlr-core-pbf-element&quot;]/div[@class=&quot;gdlr-core-tab-item gdlr-core-js gdlr-core-item-pdb  gdlr-core-left-align gdlr-core-tab-style1-horizontal gdlr-core-item-pdlr&quot;]/div[@class=&quot;gdlr-core-tab-item-wrap&quot;]/div[@class=&quot;gdlr-core-tab-item-title-wrap clearfix gdlr-core-title-font&quot;]/div[@class=&quot;gdlr-core-tab-item-title&quot;]</value>
      <webElementGuid>d604491b-4d09-4725-bccb-568f28ab479a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rrc-page-wrapper']/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[4]</value>
      <webElementGuid>52a58381-884d-460c-a0b9-feb4ff4a8591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIVITIES'])[1]/following::div[1]</value>
      <webElementGuid>e1eee632-36f4-4cf1-ad8c-45869438418b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VISION &amp; MISSION'])[1]/following::div[2]</value>
      <webElementGuid>3282f0e3-ba22-417c-a27d-44e297f7dc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NATURE CLUB'])[2]/preceding::div[1]</value>
      <webElementGuid>d40d01e7-7c51-4fbc-8ed3-342bc43f2969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here'])[1]/preceding::div[3]</value>
      <webElementGuid>0f58b976-041f-4350-8c28-1189688ee06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GALLERY']/parent::*</value>
      <webElementGuid>a1c17aab-9f27-474c-aaea-437b2ab8bf0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[4]</value>
      <webElementGuid>09d8f253-b35a-47cc-afa1-83b29cff7031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'GALLERY' or . = 'GALLERY')]</value>
      <webElementGuid>c889c1d3-3a81-469c-a7d1-25b5e7a5d74b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
