<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__ndfHFb-c4YZDc-cYSp0e-DARUcf-PLDbbf</name>
   <tag></tag>
   <elementGuidId>620e998e-1887-4ac3-ba0d-146ffc38dd87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div[4]/div/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ndfHFb-c4YZDc-cYSp0e-DARUcf-PLDbbf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.ndfHFb-c4YZDc-cYSp0e-DARUcf-PLDbbf >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>44971bf9-c1a1-40e1-b2ec-6c9b86fa8cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ndfHFb-c4YZDc-cYSp0e-DARUcf-PLDbbf</value>
      <webElementGuid>ca4f9c0d-4aa8-4814-a317-0430ef9c7a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;yYWAMb bvmRsc vhoiae LgGVmb ndfHFb-c4YZDc-uoC0bf ndfHFb-c4YZDc-qbOKL-OEVmcd&quot;]/div[@class=&quot;ndfHFb-c4YZDc ndfHFb-c4YZDc-AHmuwe-Hr88gd-OWB6Me dif24c bvmRsc ndfHFb-c4YZDc-TSZdd ndfHFb-c4YZDc-vyDMJf-aZ2wEe ndfHFb-c4YZDc-i5oIFb vhoiae LgGVmb ndfHFb-c4YZDc-uoC0bf&quot;]/div[@class=&quot;ndfHFb-c4YZDc-K9a4Re&quot;]/div[@class=&quot;ndfHFb-c4YZDc-K9a4Re-nKQ6qf ndfHFb-c4YZDc-TvD9Pc-qnnXGd&quot;]/div[@class=&quot;ndfHFb-c4YZDc-cYSp0e ndfHFb-c4YZDc-oKVyEf&quot;]/div[@class=&quot;ndfHFb-c4YZDc-cYSp0e-s2gQvd ndfHFb-c4YZDc-s2gQvd&quot;]/div[@class=&quot;ndfHFb-c4YZDc-cYSp0e-Oz6c3e ndfHFb-c4YZDc-cYSp0e-DARUcf-gSKZZ ndfHFb-c4YZDc-neVct-RCfa3e&quot;]/div[@class=&quot;ndfHFb-c4YZDc-cYSp0e-DARUcf&quot;]/div[@class=&quot;ndfHFb-c4YZDc-cYSp0e-DARUcf-PLDbbf&quot;]</value>
      <webElementGuid>6823aaea-ad21-400e-9371-e43275368e14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div/div/div[3]/div</value>
      <webElementGuid>4775eb99-8a3d-4114-9150-5038d476c6e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
