<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Learn More_div_1dd7_73</name>
   <tag></tag>
   <elementGuidId>7ce472bc-6356-47d3-9221-d6130e22cf6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_1dd7_73']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div_1dd7_73</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#div_1dd7_73</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6e2096ea-8a3c-4255-b33b-286005436a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gdlr-core-pbf-background gdlr-core-parallax gdlr-core-js</value>
      <webElementGuid>1d6fcbaa-b11e-4677-9bb7-b8e54599b5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div_1dd7_73</value>
      <webElementGuid>b6e7b022-79f1-4472-aeca-c3c3e125e7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parallax-speed</name>
      <type>Main</type>
      <value>0.2</value>
      <webElementGuid>82c339b0-fb7b-4d0d-9951-3e902c37b57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_1dd7_73&quot;)</value>
      <webElementGuid>beee13a1-96b8-4250-b19e-99b0a505fe5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div_1dd7_73']</value>
      <webElementGuid>1b700842-37c3-4087-99de-fe52c72c1b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_1dd7_72']/div/div</value>
      <webElementGuid>987e7c65-29f4-4767-82db-b66e2e2d3fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div</value>
      <webElementGuid>377ea2a4-1be3-40de-8300-d03b14f3bf51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'div_1dd7_73']</value>
      <webElementGuid>b94a20e5-2169-4681-b93d-13488ea00a37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
