<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Learn More_div_1dd7_76</name>
   <tag></tag>
   <elementGuidId>e8eb94ad-16ea-45bb-aa79-81cd1d9b8f87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_1dd7_76']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div_1dd7_76</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#div_1dd7_76</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a5148cf-986e-4150-a6dc-025f9b26bdca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gdlr-core-image-item-wrap gdlr-core-media-image  gdlr-core-image-item-style-rectangle</value>
      <webElementGuid>400df8ba-b03e-4335-b592-0845980dc2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div_1dd7_76</value>
      <webElementGuid>1ee12272-421c-4502-8ac1-5c76fe006583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_1dd7_76&quot;)</value>
      <webElementGuid>3db00b3d-fc20-46db-9fa5-466531aeb6c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div_1dd7_76']</value>
      <webElementGuid>f0c03286-5f40-4cab-8692-b9a0c4181969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_1dd7_75']/div</value>
      <webElementGuid>b7b23cd0-dad7-44be-aa30-6f947caf7ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn More'])[4]/following::div[8]</value>
      <webElementGuid>897bce8f-7795-4a3e-8421-63bbd8f3f8b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn More'])[3]/following::div[15]</value>
      <webElementGuid>e20c65ef-d4b6-418a-9bc9-87a910c6262a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RRC NAAC VISIT'])[1]/preceding::div[1]</value>
      <webElementGuid>eb0d7f36-f188-4f9d-873b-c21ceb052ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day Order'])[1]/preceding::div[8]</value>
      <webElementGuid>3a3b81b4-ecc9-4514-99e3-a7c3155078d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/div</value>
      <webElementGuid>0398fca3-b699-4399-98aa-4282bac3517b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'div_1dd7_76']</value>
      <webElementGuid>4af818a7-00ad-4f51-aa69-bf937d5a010e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
