<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ACTIVITIES</name>
   <tag></tag>
   <elementGuidId>025bc413-8133-43f6-b39c-9f409d5f01ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rrc-page-wrapper']/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;ACTIVITIES&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>88a29391-b570-4af0-beb5-31e9cd231f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gdlr-core-tab-item-title</value>
      <webElementGuid>dcd7af02-c0bf-436c-9e4c-7af63866da4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab-id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4a96f420-1300-479d-a87b-6479b8aa2153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACTIVITIES</value>
      <webElementGuid>91d72bd8-c8ca-49cd-bde0-f5e0883afc21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rrc-page-wrapper&quot;)/div[@class=&quot;gdlr-core-page-builder-body&quot;]/div[@class=&quot;gdlr-core-pbf-section&quot;]/div[@class=&quot;gdlr-core-pbf-section-container gdlr-core-container clearfix&quot;]/div[@class=&quot;gdlr-core-pbf-element&quot;]/div[@class=&quot;gdlr-core-blog-item gdlr-core-item-pdb clearfix  gdlr-core-style-blog-image&quot;]/div[@class=&quot;gdlr-core-pbf-wrapper&quot;]/div[@class=&quot;gdlr-core-pbf-wrapper-content gdlr-core-js&quot;]/div[@class=&quot;gdlr-core-pbf-wrapper-container clearfix gdlr-core-container&quot;]/div[@class=&quot;gdlr-core-pbf-element&quot;]/div[@class=&quot;gdlr-core-tab-item gdlr-core-js gdlr-core-item-pdb  gdlr-core-left-align gdlr-core-tab-style1-horizontal gdlr-core-item-pdlr&quot;]/div[@class=&quot;gdlr-core-tab-item-wrap&quot;]/div[@class=&quot;gdlr-core-tab-item-title-wrap clearfix gdlr-core-title-font&quot;]/div[@class=&quot;gdlr-core-tab-item-title&quot;]</value>
      <webElementGuid>30739f7b-4d52-4772-b045-bc7c65d53598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rrc-page-wrapper']/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[3]</value>
      <webElementGuid>545df9c0-1ffa-4348-be9a-a604aecf9f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VISION &amp; MISSION'])[1]/following::div[1]</value>
      <webElementGuid>7ae9681c-d261-42cd-9d02-759ebd579af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ABOUT'])[1]/following::div[2]</value>
      <webElementGuid>118afd03-ebc1-4ff3-9882-87b69887cfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GALLERY'])[1]/preceding::div[1]</value>
      <webElementGuid>f36aff60-6ba3-4b11-bbb6-57d0a6025132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NATURE CLUB'])[2]/preceding::div[2]</value>
      <webElementGuid>30503796-e51c-4a9f-aa28-40fe91b6cf4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACTIVITIES']/parent::*</value>
      <webElementGuid>7760af36-19bc-4bc5-95e6-faa3915cfc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]</value>
      <webElementGuid>e282df64-c4ec-4b99-886d-ef727cede0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ACTIVITIES' or . = 'ACTIVITIES')]</value>
      <webElementGuid>f3c8f1ff-5ea4-49b2-a9df-26a4f8d204ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
